### ISSUE TITLE
URL & path in markdowns

### ISSUE THREAD

**Issue by R4ph3rd** [AtelierNum/AtelierNum.github.io#12]
- [x] ajouter des id à tous les titres
- [x] placer des liens ancrage à tous les liens vers des sections
- [x] déterminer si un lien redirige vers une source externe ou interne, auquel cas il faut parser le nouveau markdown

**Comment by R4ph3rd** [comment]
Problème à régler dans les markdowns : 
certains liens vers des repos recursifs peuvent être retrouvés avec une adresse www ( avec htttp ), et d'autres sont pointés avec des paths relatifs ( [./repo] ).

Il faut soit modifier les id des projets de façon à ce que l'id corresponde au nom du repo github ( fonctionne si tous les repos n'ont pas des noms sensibles utf-8 ou à la casse ), soit faire des paths relatifs sur tous les liens.
Dans tous les cas, il me semble quand même judicieux de mettre des ids qui respectent la nomenclature déjà adoptée par @b2renger pour le nommage de ses repos, parce que le nommage actuel des id n'est pas terrible.

**Comment by R4ph3rd** [comment]
Dernier point à fixer : Tout est bon ( en principe ) dans les markdowns principaux, mais il faut adapter l'algo pour les markdowns qui sont dans un repo recursif.

**Comment by R4ph3rd** [comment]
C'est fait sur la base de l'exemple de jeux_electroniques_1819. A tester sur d'autres repos.

**Comment by b2renger** [comment]
Nickel, hyper propre, pas d'autres readme pour l'instant. 
Mais de futures à venir (projet électronique 1920 / workshop arcade 20 et restructuration du repo arduino)
