### ISSUE TITLE
Add the possibilitiy to embed videos

### ISSUE THREAD

**Issue by b2renger** [AtelierNum/AtelierNum.github.io#13]
Parse a youtube or vimeo link from a markdown to display the video embeded in the webpage.

The video will not be playable in a github markdown readme but embeded in the website.

**Comment by R4ph3rd** [comment]
Feature enable for iframes : 
you have to write in a parent div with a **video_container** class. Remove default sizes given by Youtube or Vimeo : 
```html
<div class="video_container">
   <iframe ></iframe>
</div>
```

It will display it with the maximum width of the parent component ( aka markdownReader ), conserving the 16/9 ratio. Tested with a Vimeo Iframe.
