### ISSUE TITLE
Road to Beta - v0.2

### ISSUE THREAD

**Issue by R4ph3rd** [AtelierNum/AtelierNum.github.io#14]
- [x] Corriger l'issue #9 
- [x] Responsive ! 
- [x] Version mobile
- [ ] Copy to clipboard buttons dans les sections code
- [x] Ajouter plusieurs langages dans le highliter ( Java, C#, C ++ ... )
- [x] Classer les articles par date (dans la page d'accueil au moins)

**Comment by AtelierNum** [comment]
[ ] Change header language

**Comment by R4ph3rd** [comment]
Erreur de ma part. J'ai appuyé sur le mauvais bouton.
J'ai finalisé les dernières petites corrections, et mis un logo en défonce de blanc dans le footer. Cela peut convenir ?

**Comment by R4ph3rd** [comment]
Le site est entièrement responsive sur Firefox. J'ai vu que ça déconnait pas mal sur Chrome, mais au vu des problèmes qui apparaissent, ça me semble être simplement parce qu'il faut que je duplique un certain nombre de propriétés pour les déclarer avec tous les préfixes adaptés pour tous les navigateurs. Mais sur Firefox ça me semble honnête

**Comment by R4ph3rd** [comment]
Push avec des modifs pour adapter sur différents navigateurs (la scrollbar maison reste à retravailler, mais elle n'est de toutes manières pas encore terminée). Plusieurs bug d'affichages sur mobile ont été corrigés.
