### ISSUE TITLE
Road to Alpha release

### ISSUE THREAD

**Issue by R4ph3rd** [AtelierNum/AtelierNum.github.io#3]
- [x]  fix header display bug
- [x]  set a thumbnail for projects/courses/ressources
- [x]  define a logo for ateliernum
- [x]  set on sticky nav index
- [x]  dropdown sections in index
- [x]  projects / ressources / courses global pages to do
- [x]  about page to do
- [x] wave form in top of documentation pages
- [x] position/overlay of the copy code button must be fixed
- [x] fix links to readme, repos & images issues

**Comment by R4ph3rd** [comment]
Une première version est "fonctionnelle" concernant l'import des markdowns, à partir d'un fichier json les listant.
Ils sont pour le moment importés en local avec un script, le temps de fixer un bug lié au lifecycle de Vue.js quand on importe le contenu du markdown depuis une source distante.
Les instructions pour builder le site en localserver sont indiquées sur le readme de la branche src.

**Comment by AtelierNum** [comment]
@R4ph3rd c'est pas mal du tout chouette boulot !

Je vais ajouter du contenu très bientôt, en tout cas j'ai pas eu de souci à puller / builder etc.

**Comment by b2renger** [comment]
Moi aussi je trouve ça chouette @R4ph3rd !

**Comment by R4ph3rd** [comment]
Cool moi aussi je trouve ça chouette @R4ph3rd  !

**Comment by R4ph3rd** [comment]
Manque plus qu'un logo et on peut lancer la première release !

**Comment by b2renger** [comment]
On va partir avec ce logo pour cette release je pense !
