### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by AtelierNum** [AtelierNum/AtelierNum.github.io#4]
add markdown-it-vue to node modules

**Comment by R4ph3rd** [comment]
Le composant markdown-it-vue n'est en principe plus utilisé ; il a servi pour une version de test précédente. A-t-il posé problème au build ? 
Actuellement l'import des markdowns se fait au travers du router, selon le route path ( l'objet vue contenant notamment l'url, grossièrement ), avec markdown-loader.

**Comment by b2renger** [comment]
sur la partie npm install pas de bugs

mais sur la partie"run serve" il a été déclaré comme manquant, du coup j'ai du l'installer manuellement.

et ensuite plus de souci

**Comment by R4ph3rd** [comment]
ok ; il doit rester un import quelque part dans un des composantns ; je le supprimerai quand tu auras fini de pusher tes commit

**Comment by R4ph3rd** [comment]
Je rouvre l'issue après avoir rencontré un autre pb de build ( tout à fait différent du précédent) :
après avoir des corrections pour li'ssue #5 , et lancé le script getContent.js ( remplaçant getCourses.js), l'app ne pouvait se builder. Je me suis aperçu ( après quelques menues recherches dans l'historique git ) que les nouveaux markdowns importés semblent être la source du problème. Je vois deux possibilités : 
- ils sont trop long pour être chargés correctement comme des modules js et importés dans l'app, ce qui la fait planter. mais dans ce cas le md **Introduction_Arduino** de taille relativement similaire, devrait également poser problème
- les fichiers sont vraiment conséquents, et en empiler plusieurs ainsi, et les utiliser comme modules peut potentiellement surcharger webpack ( qui s'occupe de tout agglomérer pour builder l'app, si je ne me trompe pas ). 
Dans ce cas, il y a peut être une limite à débloquer quelquepart pour faire sauter ce verrou, ou changer complètement de méthode d'import.

**Comment by R4ph3rd** [comment]
J'ai cependant supprimé les markdowns pour que l'on puisse builder l'app et faire les corrections encore nécessaires en attendant de fixer ce bug, le dernier push sur la branche src est donc fonctionnel.

**Comment by b2renger** [comment]
a priori les markdowns peuvent être ajoutés au .gitignore, non ?

**Comment by b2renger** [comment]
Pour moi le process de builder le site plante : 

```
mac-brecoules-5:App b.recoules$ npm run serve

> ateliernum@0.1.0 serve /Users/b.recoules/Documents/EDNA/git_ateliernum/AtelierNum.github.io/App
> vue-cli-service serve

 INFO  Starting development server...
40% building 178/203 modules 25 active ...it_ateliernum/AtelierNum.github.io/App/src/assets/markdowns/workshop_alt_ctrl.md?vue&type=template&id=36ab2d62&^
```

ça plante pas toujours sur le même projet

**Comment by R4ph3rd** [comment]
J'ai résolu le problème initial d'import des markdowns depuis une url, ce qui permet d'éviter ce nouveau problème de chargement des modules markdowns.
Je croyais initialement que mes markdowns ne s'importaient pas car le composant qui les parsait n'était as réactif, et une fois le hook "mounted" passé, je ne pouvais plus lui passer de données. Je m'étais simplement trompé dans ma fonction d'appel HTTP, en voulant accéder à une variable de mon composant vue, je créais en réalité une variable dans ma fonction d'appel : 
`
ar xmlhttp;
      let _vue = this ; // je store l'instance vue dans une variable pour y accéder après
      
      if (window.XMLHttpRequest) { // code for IE7+, Firefox, Chrome, Opera, Safari
        xmlhttp = new XMLHttpRequest();
      } else { // code for IE6, IE5
        xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
      }
      xmlhttp.onreadystatechange = function() {
        if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
          // this.readme =  xmlhttp.responseText ; => voilà l'erreur : this se réfère non pas à mon composant vue, mais à ma fonction xmlttp ; je ne modifiais donc pas le contenu de ma data !
          _vue.readme = xmlhttp.responseText ;
          _vue.md_loaded = true ;
        }
      }

      xmlhttp.open("GET", this.getContent.url, true);
      xmlhttp.send();
`

L'import des markdowns de manière dynamique est donc réglé, il y a une dernière chose à ajouter que je faisais dans le script **getContent.js** : permuter les path locaux en url globales. Je fais ça dans le prochain commit.

**Comment by R4ph3rd** [comment]
J'ai oublié de mentionner l'issue dans les commits, mais les deux derniers la concerne bien : 
- le premier ajoute l'url parser dans le composant
- le second passe la function servant à créer un index à partir des titres du markdown dans un fontctionnement semblable à l'asynchrone : elle attend que le markdown soit bien chargé pour s'effectuer au prochain "tick" de Vue.

**Comment by b2renger** [comment]
Bon ben c'est top !

J'essaierai de rajouter encore du contenu rapidement.

Petit truc les ressources renvoient vers le readme d'arduino plutôt que d'ouvrir la page :) 

On pourra peut-être pusher un build avec pas mal de contenu pour proposer à des testeurs de tester !

**Comment by R4ph3rd** [comment]
>  On pourra peut-être pusher un build avec pas mal de contenu pour proposer à des testeurs de tester !
Bonne idée, il reste juste un problème ou de layout à regler encore, au moins pour une version desktop avant !

> Petit truc les ressources renvoient vers le readme d'arduino plutôt que d'ouvrir la page :)
C'est à dire ? Ils doivent ouvrir des readme non ?

**Comment by R4ph3rd** [comment]
Je n'avais pas pullé, j'ai compris ; c'est modifié ; les ressources renvoient bien vers les ressources externes.
