### ISSUE TITLE
Split Courses / Projects / Ressources

### ISSUE THREAD

**Issue by b2renger** [AtelierNum/AtelierNum.github.io#5]
Il faudrait splitter les différents fichiers json qui répértorient les cours / projets et ressources

En gros cours et projets ça sera du markdown depuis github le plus souvent, mais les ressources peuvent être des ressources externes qui ne seront que très rarement dans ce format et dans l'absolu il n'est pas nécessaire de parser leur contenu pour l'afficher dans le site : au contraire il faut mieux renvoyer vers leur site.

**Comment by R4ph3rd** [comment]
On peut considérer dans un premier temps que toutes les ressources seront externes, et donc n'utiliser que des liens de redirection.
Tu peux effectivement faire un fichier séparé pour les cours et les projets, que tu rassembles dans le fichier global coursesList.json ( qui devra être renommé par ailleurs ).

**Comment by AtelierNum** [comment]
j'étais parti sur 
- coursesList.json
- projectsList.json
- ressourcesList.json

et des scripts node correspondant (sauf pour les ressources - qui renverront directement vers la page)

**Comment by R4ph3rd** [comment]
C'est possible, mais pour faciliter le montage des routes vers les différentes pages, ce sera vraiment plus simple si l'on agglomère tout ça un json global, et un seul script node pourra suffire. Je vais modifier ça.
