### ISSUE TITLE
Structure de données pour les cartes

### ISSUE THREAD

**Issue by b2renger** [AtelierNum/AtelierNum.github.io#6]
Dans la structure de données des cartes :

- on a "name" et "id" à quoi sert cette différentication en deux champs ?
- il nous faudrait probablement un champ "author" aussi

**Comment by R4ph3rd** [comment]
Elle sert à éviter les problèmes d'utf-8 et autres : 
- id étant utilisée pour définir l'url et deux trois autres fonctions qui ne sont pas compatibles avec l'utf-8, il faut utiliser une string qui peut etre differente du véritable nom, de préférence en miniscules
- name sert donc à stocker la string compatible utf-8, le véritable nom du projet

Le champ author est effectivement une bonne idée, tu pourras le rajouter quand tu éditeras le json
