### ISSUE TITLE
Add social networks links

### ISSUE THREAD

**Issue by b2renger** [AtelierNum/AtelierNum.github.io#7]
- instagram ateliernum
- discord ateliernum

**Comment by R4ph3rd** [comment]
Socials ajoutés dans le footer ( qui manque d'ailleurs peut être d'informations, légales (?) notamment )
Le lien discord est un lien d'invitation que j'ai crée, et affiche donc un message indiquant que je l'ai invité sur le discord de l'atelier num. Ca ne me pose pas de problème d'avoir mon pseudo discord affiché, mais peut être est-ce préférable que ce soit celui de @b2renger , dans cas il faudra que tu en crées un toi-même et édite le lien dans le composant **footer** qui se trouve dans le folder **src/components/organismes/footer.vue**.

**Comment by b2renger** [comment]
Nickel,
je modifierai le lien effectivement j'ai un lien permanent qui est déjà en circulation
Oui mentions légales effectivement : t'as un modèle pour ce genre de choses ?

**Comment by R4ph3rd** [comment]
Non, peut être que simplement reprendre celles de l'école peut suffire ?

**Comment by R4ph3rd** [comment]
readme et about page ajoutés, manque plus que le lien discord pour clore cette issue !
