### ISSUE TITLE
Readme errors

### ISSUE THREAD

**Issue by R4ph3rd** [AtelierNum/AtelierNum.github.io#8]
**Thread pour lister toutes les erreurs liées aux différentes syntaxes des readme.**

- Introduction P5Js
Toutes les sections sont contenues dans des bannières html href (étrange façon de faire par ailleurs), ce qui empêche à la fonction créant l'index de navigation de trouver les titres de section.

**Comment by b2renger** [comment]
- Projets jeux électroniques : les liens vers les documentation renvoient vers des pages github et non vers des pages internes au site.

- Introduction arduino : les liens de la TOC renvoient vers le readme github

- Introduction processing : pbs de formattage de titres.

**Comment by R4ph3rd** [comment]
Il faut absoluement faire attention à ne pas avoir deux id identiques entre deux projets / cours / ressources, listés, sans quoi le path sera identique pour les deux, et ça crée des conflits. J'en ai reperé deux ou trois dans les json.

**Comment by R4ph3rd** [comment]
Dans le reamde workshop 1920, il y a beaucoup de confusions avec celui de 1819 : 
* Le H1 qui affiche 1819
* Tous les liens vers les cahiers de recherche pointent une adresse contenant 1819. ( erreur 404 sur Gitub, et avec le parser sur le site, ça renvoie vers la page du 1819 )

**Comment by b2renger** [comment]
> Dans le reamde workshop 1920, il y a beaucoup de confusions avec celui de 1819 :
> 
> * Le H1 qui affiche 1819
> * Tous les liens vers les cahiers de recherche pointent une adresse contenant 1819. ( erreur 404 sur Gitub, et avec le parser sur le site, ça renvoie vers la page du 1819 )

Ok c'est réglé

**Comment by b2renger** [comment]
Listes des repos (tickés si vérifiés et ok) 

Cours : 
- [ ] Introduction processing
- [x] Introduction arduino
- [x] Introduction p5js
- [ ] Introduction pure-data
- [x] Image alteration 
- [ ] motifs génératifs
- [ ] gestes de l'ennui
- [ ] typographie
- [ ] patatap
- [ ] workshop PCD processing
- [ ] workshop PCD p5js
- [ ] Sound design références
- [ ] Game From Scratch
- [ ] EntomologiK

Projets : 
- [x] CC2020
- [ ] gestes de l'ennui 1920
- [ ] patatap 1920
- [ ] game from scratch 19
- [ ]  motifs génératifs 19
- [ ] CC2019
- [x] Jeux électroniques 1819
- [ ] patatap 1819
- [ ] dis-information signal
- [ ] game from scratch 18

**Comment by R4ph3rd** [comment]
Jeux électroniques 1819 : Le readme Duel n'affiche aucune image correctement car le path n'est pas correct :
```markdown
![une image](media/image.gif)
// alors que cela devrait être :
![une image](Media/image.gif)
```
Les parseurs markdown étant en js, ils sont sensibles sensible à la casse.

**Comment by b2renger** [comment]
souvent une fois en ligne oui, alors que en local ça passe... c'est pas la première fois que je vois ce genre de chose.

**Comment by b2renger** [comment]
Ok normalement on est bon !
