### ISSUE TITLE
description des cartes tronquées

### ISSUE THREAD

**Issue by b2renger** [AtelierNum/AtelierNum.github.io#9]
Certaines description sont tronquées d'autres pas.
Il faudrait uniformiser et permettre de voir le texte complet avec un petit '+' pour le faire apparaitre.

**Comment by b2renger** [comment]
Je m'attendais plus à un petit '+' qui permet d'ouvrir la description en entier :)

**Comment by R4ph3rd** [comment]
J'ai oublié de mentionner cette issue dans le dernier commit, mais la taille des small cards est maintenant passée à 300px, ce qui laisse environ 3 lignes de texte disponible :
```
Abbleton Live in browser introduction to sound synthesis ! e.g. How to build synths. qq caractères en +```
Pour le reste des cards, comme il a été dit, il vaut mieux éviter ce '+' qui serait une zone de clic dans une zone de clic, un petit jeu de chat et de souris vicieux, alors que l'entièreté de la description est visible ensuite dans la page de documentation.
